---

- name: Remove all previous Docker packages
  ansible.builtin.dnf:
    name:
      - moby-engine
      - runc

- name: Setup Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    baseurl:
      - https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey:
      - https://download.docker.com/linux/fedora/gpg

- name: Install all Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable Docker service
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
    daemon_reload: true
